# Generated by Django 5.2.1 on 2025-05-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
